[package]
name = "cosmic-theme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = "0.6"
anyhow = "1.0"
hex = "0.4.3"
kmeans_colors = { git = "https://github.com/okaneco/kmeans-colors", features = ["palette_color"], default-features = false }
gdk-pixbuf = "0.15.10"
gio = "0.15.10"
float-cmp = "0.9.0"

